name: Build and Push Docker Image

on:
  push:
    tags:
    - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Download Source Code
        run: |
          bash ./download_source.sh

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: chomu/abc_py:latest, chomu/abc_py:amd64
